language: scala
scala:
   - 2.10.6
   - 2.11.8
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M -J-Xms512m -J-Xmx512m test
